### ISSUE TITLE
bids-validator singularity container?

### ISSUE THREAD

**Issue by yarikoptic** [bids-apps/base_validator#1]
Could not find it upon quick look at singularity-hub.org, so before remaking from docker thought to ask ;)

**Comment by chrisgorgo** [comment]
Not that I know of.

**Comment by Remi-Gau** [comment]
closing but feel free to reopen if needed

**Comment by yarikoptic** [comment]
FTR: we keep singularity containers for all bids apps available from  https://datasets.datalad.org/?dir=/repronim/containers/images/bids . The archive of singularity-hub.org is also nearby: https://datasets.datalad.org/?dir=/shub
